oliverschwendener/ueli

README.md, src/js/Plugins/InstalledPrograms.js
Loading files async from file system is faster and does not block the UI that hard. Node >= 7.8.0 is required because of async/await features.
=> Load files async from filesystem

.gitignore, gulpfile.js, main.html, package.json, src/ts/main.ts, src/ts/renderer.ts, tsconfig.json
Moved the renderer.js to typescript. With that the build folder was changed to dist in the root folder.
These are the benefits:
- The build-files separated from sources
- Removes complexity
=> Move renderer.js to typescript

src/common/helpers/logger-helpers.ts, src/common/logger/dev-logger.ts, src/common/logger/production-logger.ts
This adds stack traces of errors to logs.
Source: https://github.com/winstonjs/winston/issues/1338#issuecomment-482784056
=> Log stack traces of errors

src/main/plugins/control-panel-plugin/control-panel-items-retriever.ts
This makes the plugin work under Windows 8.1 where by default Powershell 4.0 is installed.
=> made control panel plugin compatible with Powershell 4.0

src/main/plugins/application-search-plugin/windows-app-icon-generator.ts
Use `Test-Path` with parameter `-LiteralPath` instead of `-Path`. `-Path` interpretes wildcard characters, which causes an error when file names contain characters like `[` or `]`.
=> Fix for issue #343

src/renderer/user-input-component.ts
The removed id of the user input control (commit 5a4fbd7c7d) broke scrolling on arrow-down/up in search results (search-results-component scrollIntoView() uses the id to get the element).
=> Fix search results scrolling

src/main/plugins/uwp-plugin/uwp-apps-retriever.ts
This fixes a bug in the UWP apps retriever that prevented newly installed apps from being detected when index was refreshed.
=> Fix UWP plugin index refresh

src/main/executors/file-searchers.ts
This fixes issue #401.
File searcher must set the output encoding to UTF8.
=> File Searcher should use UTF8 encoding

src/main/plugins/control-panel-plugin/control-panel-plugin.ts
There are encoding issues with node-powershell when the script contains non-ASCII characters, like umlauts (äöü). That's why control panel items like `Geräte und Drucker` could not be opened. Using `executeCommand` fixes the issue.
=> Fix opening control panel items with non-ASCII characters

src/main/plugins/everything-plugin/everything-searcher.ts
This fixes the second issue from #401.
=> EverythingSearcher should use UTF8 encoding

src/main/executors/application-searcher.ts, src/main/plugins/application-search-plugin/production-application-repository.ts, src/main/production/production-search-engine.ts
The application searcher scans directories defined by the user. These directories can contain files that cannot be accessed and the directories could not exist anymore. Currently this causes the application searcher to throw an error so that no applications are indexed at all. I think we can just ignore all errors.
=> ignore Windows application searcher errors

src/renderer/search-results-component.ts, styles/app.css
Fixes #418 
The overlay was causing this issue with transparent background 
so I removed it and decreased the opacity a little bit which kinda similar to the intended look I guess but doesn't cause issues with transparent background.
=> fix results item overlay on transparent bg

src/renderer/user-input-component.ts
Hello! Loving ueli, thanks for maintaining.
I use a lot of Vim-centric key bindings, and would love to be able to navigate the ueli results menu using Ctrl+N and Ctrl+P in addition to arrow keys per the common Vim paradigm.
This PR adds support for navigating the results list with Ctrl+N and Ctrl+P, in addition to using the arrow keys.
Thanks in advance for your attention!
=> Navigate results list with Ctrl+N and Ctrl+P

src/common/translation/english-translation-set.ts, src/common/translation/german-translation-set.ts, src/common/translation/russian-translation-set.ts, src/common/translation/translation-set.ts, src/common/translation/turkish-translation-set.ts, src/main/plugins/operating-system-commands-plugin/mac-os-operating-system-command-repository.ts
Loving using ueli - thanks for maintaining it!
I noticed a "sleep" OS command is implemented for Windows, but doesn't exist for MacOS. This PR adds a sleep command for MacOS, following the same pattern of existing OS commands of invoking AppleScript and using the icon from the Windows sleep command.
Includes an English and German localization, but missing Russian. What is the standard practice for localizations? Should I @mention the original contributor of the Russian localization? Also happy to do the same to validate the German.
=> Add MacOS "sleep" command

src/main/plugins/dictionary-plugin/google-dictionary-definition-retriever.ts
The dictionary has stopped working for a while now because of outdated api url.
=> update dictionary api

src/main/user-input-history-manager.test.ts, src/main/user-input-history-manager.ts
Having duplicates in userInput history manager is inconvenient, A lot of times I open an application like 5 times in a row and It makes no sense to cycle through the same 5 input history.
=> filter out duplicates from input history manager

src/main/main.ts
this option is needed on mac to stop fullscreen apps from switching desktops when toggleing Ueli
=> added visibleOnFullScreen

src/main/executors/commandline-executor.ts, src/main/plugins/commandline-plugin/shells.ts
Added the option to select "Powershell in Windows Terminal" as the shell in the commandline plugin.
This runs the command in Powershell in the new Windows Terminal
=> Added "Powershell in Windows Terminal" to the commandline plugin

src/main/plugins/color-converter-plugin/color-converter-plugin.ts, src/main/plugins/control-panel-plugin/control-panel-item.ts, src/main/plugins/dictionary-plugin/dictionary-plugin.ts, src/main/plugins/mdfind-plugin/mdfind-plugin.ts, src/main/plugins/operating-system-settings-plugin/macos-operating-system-setting-repository.ts, src/main/plugins/translation-plugin/translation-plugin.ts, tsconfig.json
This PR enables `strictPropertyInitialization` flag for the typescript compiler, and makes the relevant code changes
This way, we can gradually enable flags, and eventually enable the comprehensive `strict` flag.
=> the road to strict mode: enable strictPropertyInitialization

src/main/plugins/currency-converter-plugin/currency-converter-plugin.ts
* Adds support for the use of the "to" keyword for currency conversions, e.g. `1 GBP to AUD`
* Fixes an issue where the input validator accepted whitespace, but the action was not set up to handle this whitespace
=> Add 'to' keyword support for currency conversions

src/main/plugins/control-panel-plugin/control-panel-items-retriever.ts
If a profile was present with outputs, it broke the control panel icon retrieval.
=> Retrieve control panel icons with noProfile: true

src/main/executors/command-executor.ts, src/main/plugins/uwp-plugin/uwp-apps-retriever.ts
Use `child_process.spawn()` to retrieve UWP apps to avoid maxBuffer length exceeded error. This should fix #610.
=> Use spawn to retrieve UWP apps

src/main/executors/websearch-suggestion-resolver.ts, src/main/plugins/websearch-plugin/websearch-plugin.ts
Some improvements and fixes for the web search plugin:
1. Descriptions of results contained URL-encoded texts:
This doesn't look nice and encoding is only necessary for the search URL. So I don't encode the texts anymore:
2. If the search prefix was part of a suggestion, it was removed:
Now, the suggestion is correctly shown:
3. There was an encoding-related problem with Google suggestions:
This could be fixed by setting a user agent...
=> Web search plugin improvements/fixes

src/main/plugins/websearch-plugin/websearch-plugin.ts
The new search suggestion feature works really well. This PR adds tab completion to web search suggestions.
There is an ugly part in the `autoComplete` method. All `webSearchEngines` are searched and compared to a part of the `executionArgument` only to recreate the web search engines prefix. But since executionArguments are built from a specific web search engines configured url template, this works quite stable.
=> Add tab completion to web search suggestions

src/main/plugins/workflow-plugin/workflow-plugin.ts, src/main/production/production-search-engine.ts
Hi,
While working with the Workflows I noticed that the commands where not firing in the terminal.  Maybe it is the kind of commands I wanted to run - but not much seemed to be happening for me.
The workflow command is now mimicking the commandline-plugin.  This change has been tested with iTerm on a Mac.  I noticed that if there are a few commands back to back they will execute on the same window. 
Related?
https://github.com/oliverschwendener/ueli/issues/644
=> Execute workflow commands in default terminal

src/main/main.ts
Discard search results if they were not retrieved for the latest user input.
This should fix #778 and #665.
=> Display search results only if they were retrieved for last user input

src/main/plugins/currency-converter-plugin/currency-converter-plugin.ts
The first word after the number is treated as the base currency and the second is treated as the target currency.
=> Also works without "in" or "to" keywords

src/main/plugins/calculator-plugin/calculator.test.ts, src/main/plugins/calculator-plugin/calculator.ts
math.js supports the symbol `null`, so `math.evaluate('null') === null`.
Typing `null` in ueli gives an exception, and the log says `Cannot read property 'toString' of null`.
ueli tries to convert the evaluation result to a string, so instead of `result.toString()` I changed it to `String(result)` to support `null`
=> [Calculator] Handle mathjs evaluating to null

src/renderer/settings/icon-component.ts, src/renderer/settings/modals/websearch-editing-modal-component.ts
Given a domain `https://[website].[domain]`. We can grab the favicon using it's url with `https://[website].[domain]/favicon.ico`.
Alongside this implementation is a fallback to the default icon if the favicon doesn't exist on `icon-component.ts`. 
Based on issue #574 which I created. After the user inputs the url and exits, the Image URL section will auto fill with the `favicon` url. 
Example of change:
=> Get favicon from websearch url

src/main/main.ts, src/main/search-engine.test.ts, src/main/search-engine.ts
Currently, when triggering a manual index refresh and one of the plugins throws an error, the `Refreshing indexes...` indication is immediately removed, even if index refreshing of other plugins is still ongoing. Also, only the first error is logged, even if multiple plugins throw errors.
This fixes the issue by using `Promise.allSettled()` instead of `Promise.all()`.
=> Handle errors of all plugins during index refresh

src/main/executors/application-searcher.ts
This fixes the new issue posted in #343 by using `Get-ChildItem` with `-LiteralPath` to ignore wildcard characters. `-Include` does not work with `-LiteralPath` so I use `Where-Object` instead. Besides this improves the performance by around 40% (on my system from ~1270 ms to ~750 ms).
=> Application search: ignore wildcard characters in paths

README.md
Using an open-source web tool called [contrib.rocks](https://contrib.rocks/preview?repo=oliverschwendener/ueli) that sync daily with [Contributors Graph](https://github.com/oliverschwendener/ueli/graphs/contributors).
=> Adding Contributors Wall to README

src/common/config/currency-converter-options.ts, src/main/plugins/currency-converter-plugin/currency-converter-plugin.ts, src/renderer/settings/currency-converter-settings-component.ts
Hey there! I would like to add the feature "Default Target Currency".
I love using ueli and do so every single day. One of the (very few) things that I thought would be nice to have is the option for setting a default target currency.
- Added an option in the settings window under the Currency Converter plugin. The option allows a person to set a default target currency.
- Added the necessary code for checking the input and converting it correctly.
To see how the feature works, simply leave out the in/to keyword and the target currency:
- I did not add translations of the name of the option, since I unfortunately don't speak any of the supported languages.
I think it is ready to be merged (except the translation part), but I am of course happy to make any changes you see fit!
Hope you …
=> Default Target Currency

src/common/config/application-search-options.ts
Most macOS apps now seem to live in `/System/Applications` so this path should be added to the default setup so users can easily open QuickTime Player and TextEdit again.
=> Add /System/Applications to default search path

src/main/main.ts
If we are not tracking the last window position (`config.generalConfig.rememberWindowPosition == false`), skip updating the config with `config.generalConfig.lastWindowPosition`.
---
For context, I personally store my `config.json` in a Git repo where I track some config files. Since I regularly move between using my laptop with monitors and on the laptop screen, the `lastWindowPosition` updates often, which creates a diff in that repo. However, I have `rememberWindowPosition` disabled.
It's a mild annoyance to reset those changes when I end up with a diff :)
=> Skip updating the config on window move if we are not tracking last window position

src/main/plugins/translation-plugin/linguee-translator.ts, src/main/plugins/translation-plugin/translation-plugin.ts
This fixes #999 by updating translation plugin to use [v2 linguee api](https://linguee-api.fly.dev/docs#/default/translations_api_v2_translations_get).
Note that this is [not an official API](https://github.com/imankulov/linguee-api/discussions/39) and does not work for all words.
Works fine:
https://linguee-api.fly.dev/api/v2/translations?query=tree&src=en&dst=de
Returns Internal Server Error:
https://linguee-api.fly.dev/api/v2/translations?query=order&src=en&dst=de
So we should find a better API.
=> Fix translation plugin

src/common/error-search-result-item.ts, src/common/translation/czech-translation-set.ts, src/common/translation/english-translation-set.ts, src/common/translation/finnish-translation-set.ts, src/common/translation/german-translation-set.ts, src/common/translation/hindi-translation-set.ts, src/common/translation/italian-translation-set.ts, src/common/translation/japanese-translation-set.ts, src/common/translation/korean-translation-set.ts, src/common/translation/portuguese-translation-set.ts, src/common/translation/russian-translation-set.ts, src/common/translation/simplified-chinese-translation-set.ts, src/common/translation/spanish-translation-set.ts, src/common/translation/traditional-chinese-translation-set.ts, src/common/translation/translation-set.ts, src/common/translation/turkish-translation-set.ts, src/common/translation/ukrainian-translation-set.ts, src/main/main.ts, src/main/plugins/ueli-command-search-plugin/ueli-command-execution-argument.ts, src/main/plugins/ueli-command-search-plugin/ueli-command-search-plugin.ts
This adds an ueli command for opening the debug log file:
Additionally this command is now used for the general error search result and thereby fixes #348:
I only updated German and English versions of the generalErrorDescription, the rest still needs to be updated.
=> Add ueli command for opening debug log

src/main/plugins/currency-converter-plugin/currency-converter.ts
This adds a fallback mechanism in the currency converter logic in case the primary URL is unavailable for whatever reason.
As suggested by @fawazahmed0 mentioned in #1043.
=> refactor: add fallback to currency converter

src/main/Core/IniFileParser/IniFileParser.test.ts, src/main/Core/IniFileParser/IniFileParser.ts
This PR should add a fix to the IniFileParser in order to handle `\r\n` line endings correctly.
=> Added test to cover `\r\n` line endings

src/main/Extensions/WebSearch/DuckDuckGoWebSearchEngine.test.ts, src/main/Extensions/WebSearch/DuckDuckGoWebSearchEngine.ts
DuckDuckGo's region parameter is supposed to be “kl”. 🧐
cf: https://duckduckgo.com/duckduckgo-help-pages/settings/params/
=> fix: Use "kl" instead of "lk" as DuckDuckGo parameter

src/common/Core/LinuxDesktopEnvironment.ts, src/main/Core/Dependencies.ts, src/main/Core/LinuxDesktopEnvironment/Contract/LinuxDesktopEnvironment.ts, src/main/Core/LinuxDesktopEnvironment/Contract/LinuxDesktopEnvironmentResolver.ts, src/main/Core/LinuxDesktopEnvironment/Contract/index.ts, src/main/Core/LinuxDesktopEnvironment/LinuxDesktopEnvironmentModule.ts, src/main/Core/LinuxDesktopEnvironment/LinuxDesktopEnvironmentResolver.test.ts, src/main/Core/LinuxDesktopEnvironment/LinuxDesktopEnvironmentResolver.ts, src/main/Core/LinuxDesktopEnvironment/index.ts, src/main/Core/index.ts, src/main/index.ts
@ke1v I added here the basic structure for a `LinuxDesktopEnvironmentResolver`. What do you think about this? Here we have a small module that is responsible of resolving the current Linux desktop environment. This can be then used by other modules like the `LinuxAppIconExtractor` or the `LinuxApplicationRepository`. You can target your implementation against this branch.
=> feat: added linux desktop environment resolver

src/main/Extensions/Base64Conversion/Base64Converter.test.ts, src/main/Extensions/Base64Conversion/Base64Converter.ts
Encoding specified for Buffer on Base64 Conversion should be “utf8”, not “binary”.
This causes that non-ASCII characters, Emoji, etc... are not encoded/decoded correctly.
For example: "thumbs-up"👍should be encoded as "8J+RjQ=="
```shell
$ printf 👍 | base64
8J+RjQ==
```
but Base64 Conversion result:
This PR fix would make the following result:
=> fix: Use "utf8" encoding for Buffer on Base64 conversion

src/main/Extensions/JetBrainsToolbox/JetBrainsToolboxExtension.ts
This PR replaces the usage of `fs.readfile()` with `FileSystemUtility.readJsonFile()` which should simplify the typing.
=> refactor(JetBrainsToolbox): use FileSystemUtility instead of fs.readfile

src/main/Core/FileSystemUtility/NodeJsFileSystemUtility.ts
Refactors some file system utility functions to use the `fs/promises` counterpart instead of callbacks.
=> Use `fs/promises` for file system utility functions

docs/Extensions/JetBrainsToolbox/README.md, src/main/Extensions/JetBrainsToolbox/JetBrainsToolboxExtension.ts, src/main/Extensions/JetBrainsToolbox/JetBrainsToolboxModule.ts
The current implementation does not show all projects. With these changes all recent project of all tools installed by the Toolbox will be shown with the icon of the tool (if no project icon is present).
=> Adjust how Jetbrains Toolbox extension loads projects

tsconfig.node.json, tsconfig.renderer.json
As eslint does not catch unused class properties we add the rule for the typescript compiler.
=> feat(tsconfig): add "noUnusedLocals" rule to prevent unused class properties

src/main/Core/TrayIcon/TrayIconManager.test.ts, src/main/Core/TrayIcon/TrayIconManager.ts, src/main/Core/TrayIcon/TrayIconModule.ts
=> refactor(TrayIcon): move event listeners from the TrayIconManager to the TrayIconModule

src/main/Extensions/CurrencyConversion/CurrencyConversion.test.ts, src/main/Extensions/CurrencyConversion/CurrencyConversion.ts, src/renderer/Extensions/CurrencyConversion/CurrencyConversionSettings.tsx
Hello (again)! I am back with the second round of default target currency! (I was the person who implemented this for the old version as well) 😅
Still love the app and still use it very frequently 🤘 So kudos! 🙏 
Fixes #1207 
I added the option for setting a default target currency. This includes updating the settings panel and a bit of the code to handle the input in the case of just writing the shorthand version.
The settings part let's the user pick only from the already selected list of currencies.
> [!note]
> _Note that I tried adding the Swiss German translation for the setting, but since I do not actually speak this language very well a quick review from someone who does would be appreciated_ 🙏
Couple of things of note:
- The chosen currency list from the settings does not seem to …
=> :sparkles: Add option for setting a default target currency

src/main/Core/ImageGenerator/Windows/WindowsApplicationIconExtractor.test.ts, src/main/Core/ImageGenerator/Windows/WindowsApplicationIconExtractor.ts
Title says it all.
Fixes potentially #1133
=> fix(WindowsApplicationIconExtractor): ignore case of file extension

src/main/Core/Autostart/AutostartManager.ts, src/main/Core/Autostart/AutostartModule.ts, src/main/Core/Autostart/DefaultAutostartManager.test.ts, src/main/Core/Autostart/DefaultAutostartManager.ts, src/main/Core/Autostart/WindowsStoreAutostartManager.test.ts, src/main/Core/Autostart/WindowsStoreAutostartManager.ts, src/main/Core/FileSystemUtility/Contract/FileSystemUtility.ts, src/main/Core/FileSystemUtility/NodeJsFileSystemUtility.ts
This fixes an issue where the autostart option wouldn't work when the app is installed through the Windows Store.
Fixes #1137
=> fix(Autostart): when app is installed through Windows Store

src/main/Extensions/JetBrainsToolbox/JetBrainsToolboxExtension.ts, src/main/Extensions/VSCode/VSCodeExtension.ts, src/renderer/Core/Search/SearchViewController.ts, src/renderer/Core/Settings/Pages/SearchEngine/SearchEngineId.tsx
This PR makes "fuzzysort" the new default search engine as (in my opinion) it leads to better search results.
=> feat: make fuzzysort new default search engine

package-lock.json, package.json, src/main/Core/CommandlineUtility/NodeJsCommandlineUtility.test.ts, vite.config.mts
This PR upgrades to vite 6 and the latest vitest version.
Test on:
=> chore: update to vite 6

src/main/Extensions/JetBrainsToolbox/JetBrainsToolboxExtension.ts, src/main/Extensions/JetBrainsToolbox/JetBrainsToolboxModule.ts
As the method `getInstantSearchResults` will be invoked on every keystroke we should keep it as lightweight as possible. This PR moves all functionality from `getInstantSearchResultItems` to `getSearchResultItems` which will be executed periodically and asynchronously, not blocking the user input field.
The behavior of the extension is unchanged (I think). @scomans Please confirm.
=> refactor(JetBrainsToolboxExtension): move resolving of search result items to `getSearchResultItems`

src/main/Extensions/VSCode/VSCodeExtension.ts
Fix bug when 2 entries where filename and folder are the same it will just open whatever the path actually is regardless of which one you press
=> [VSCode ext] Fix bug when filename and folder are the same

src/common/Core/ContextBridge.ts, src/common/Core/InstantSearchResultItems.ts, src/common/Core/index.ts, src/main/Core/Extension/Contract/Extension.ts, src/main/Core/ExtensionManager/ExtensionManager.test.ts, src/main/Core/ExtensionManager/ExtensionManager.ts, src/main/Extensions/Calculator/CalculatorExtension.ts, src/main/Extensions/ColorConverter/ColorConverterExtension.test.ts, src/main/Extensions/ColorConverter/ColorConverterExtension.ts, src/main/Extensions/CurrencyConversion/CurrencyConversion.test.ts, src/main/Extensions/CurrencyConversion/CurrencyConversion.ts, src/main/Extensions/CustomWebSearch/CustomWebSearchExtension.test.ts, src/main/Extensions/CustomWebSearch/CustomWebSearchExtension.ts, src/main/Extensions/TerminalLauncher/TerminalLauncherExtension.ts, src/main/Extensions/VSCode/VSCodeExtension.ts, src/main/Extensions/WebSearch/WebSearchExtension.test.ts, src/main/Extensions/WebSearch/WebSearchExtension.ts, src/renderer/Core/Search/Helpers/getSearchResult.test.ts, src/renderer/Core/Search/Helpers/getSearchResult.ts
The current problem is that all instant search results go after the oridnary search results. For most extensions I assume that is the right behavior but for others it would be convenient to place the instant search results at the beginning of the search result list. See [this conversation](https://github.com/oliverschwendener/ueli/pull/1279#issuecomment-2516601653) as an example.
The behavior of all existing extensions should be unchanged, as all instant search results go **after** the regular search results.
@IrishBruse @NiewView Please confirm that your extensions still behave as expected.
=> refactor(InstantSearchResults): added the option to order instant search results

src/main/Core/Terminal/TerminalModule.ts, src/main/Core/Terminal/TerminalRegistry.test.ts, src/main/Core/Terminal/TerminalRegistry.ts
In order to make testing easier this PR moves the operating system specific terminals to the bootstrap of the module.
=> refactor(TerminalRegistry): moved operating system specific terminals to module bootstrap

src/main/Extensions/ApplicationSearch/Linux/LinuxApplicationRepository.ts
Filters out any `.desktop` files not of type Application
=> fix: Improve Linux app filtering

src/main/Core/ActionHandler/ActionHandlerModule.ts, src/main/Core/SearchWindow/SearchWindowModule.ts
This is an alternative implementation to #1311.
The goal of this PR is to optimistically hide the search window before the action invocation started. This leads to better responsiveness when invoking actions.
Instead of logging an error we can also show an error box. I think that would make more sense as we should make the user aware immidiately that something went wrong. This is an example of the error box on Windows:
=> Alternative to "Improve responsiveness of app launches"

src/main/Core/SearchWindow/SearchWindowModule.ts, src/renderer/Core/I18n/getCoreResources.ts, src/renderer/Core/Search/Search.tsx, src/renderer/Core/Settings/Pages/SearchEngine/ManualRescanKeyboardShortcut.tsx, src/renderer/Core/Settings/Pages/SearchEngine/RescanShortcutHint.tsx, src/renderer/Core/Settings/Pages/SearchEngine/SearchEngine.tsx
This adds <kbd>F5</kbd> as a keyboard shortcut for rescanning. I think it is much more convenient than having to enter `rescan`.
=> Add keyboard shortcut for rescanning

src/main/Core/Autostart/AutostartModule.ts, src/main/Core/Autostart/WindowsStoreAutostartManager.test.ts, src/main/Core/Autostart/WindowsStoreAutostartManager.ts, src/main/Core/FileSystemUtility/Contract/FileSystemUtility.ts, src/main/Core/FileSystemUtility/NodeJsFileSystemUtility.test.ts, src/main/Core/FileSystemUtility/NodeJsFileSystemUtility.ts
This fixes #1137 by creating a shortcut link with target `shell:AppsFolder\\1915OliverSchwendener.Ueli_a397x08q5x7rp!OliverSchwendener.Ueli`.
I had to use a quite ugly workaround to check if the file contains the correct target since Electron's `readShortcutLink` method does return an empty target for Windows store app lnk files.
=> Fix Windows store app autostart

src/main/Extensions/VSCode/VSCodeExtension.ts
fixes #1334
VSCode Extension fix macos default command by setting it to the common install location of `/usr/local/bin/code %s`
=> VSCode Extension fix macos default command

src/main/Extensions/VSCode/Settings.ts, src/main/Extensions/VSCode/VSCodeExtension.ts, src/renderer/Extensions/VSCode/VSCodeSettings.tsx
This closes #1336 by adding a setting to show the path in the search results list.
Additional improvements:
- Changing settings no longer requires re-indexing since the settings are now applied in `getInstantSearchResultItems()`
- Improved commandTooltip translation
=> VSCode: add setting to show path

src/renderer/Core/Components/BasicSearch.tsx, src/renderer/Core/Search/CompactSearchResultListItem.tsx, src/renderer/Core/Search/DetailedSearchResultItem.tsx, src/renderer/Core/Search/Search.tsx, src/renderer/Core/Search/SearchResultItemImage.tsx, src/renderer/Core/Search/SearchResultList.tsx, src/renderer/Core/Search/SearchResultListItem.tsx, src/renderer/Core/Search/SearchResultListItemSelectedIndicator.tsx, src/renderer/Core/Search/SearchResultListLayout.ts
This PR introduces a new "layout" option on the `SearchResultList` component. Currently available are "compact" (looks like the current search results) and "detailed" which has 2 lines of text per search result item. The first line represents the search result name and on the second line we can in the future show more details. Here is how it looks:
|compact|detailed|
|---|---|
|![image](https://github.com/user-attachments/assets/430905f4-1b87-4316-bdea-b37b520b9967)|![image](https://github.com/user-attachments/assets/a68b786d-ebf3-480f-ad24-a5ab0a2bd0b8)|
=> feat: introduce search result list layout options

src/main/Extensions/ApplicationSearch/Linux/LinuxApplication.ts
This PR removes the not working drag&drop for Linux applications. I think it doesn't make sense to have it until we know how to make it actually work.
=> fix: remove not working drag and drop for linux applications

src/main/Extensions/ApplicationSearch/ApplicationSearchModule.ts, src/main/Extensions/ApplicationSearch/Windows/WindowsApplicationRepository.test.ts, src/main/Extensions/ApplicationSearch/Windows/WindowsApplicationRepository.ts
Since v9 when a folder does not exist on Windows it fails to scan other folders while in v8 it was just a warning and skipped invalid paths. This might happen when for example you're using a USB drive that might not be plugged in. I think we should keep the same behavior. This is also consistent with behavior on Linux.
=> Application Search: check folder exists on Windows

src/renderer/Core/I18n/getCoreResources.ts, src/renderer/Core/Settings/Pages/SearchEngine/ExcludedItems.tsx, src/renderer/Core/Settings/Pages/SearchEngine/SearchEngine.tsx, src/renderer/Core/Settings/Pages/index.tsx
This PR moves the excluded items to a separate settings page as suggested in #1326.
=> refactor: move excluded items to separate settings page

src/renderer/Core/I18n/getCoreResources.ts, src/renderer/Core/Search/ConfirmationDialog.tsx, src/renderer/Core/Search/Search.tsx, src/renderer/Core/Search/SearchViewController.ts
This PR refactors the ConfirmationDialog in order to use the `SearchViewController`'s `invokeAction` function. Additionally it adds missing translations and fixes a bug that causes the search window to hide instead of just closing the confirmation dialog when pressing "Esc".
=> refactor(ConfirmationDialog): use invokeAction from controller

src/renderer/Core/I18n/getCoreResources.ts, src/renderer/Core/Search/SearchViewController.ts, src/renderer/Core/Settings/Pages/General/General.tsx, src/renderer/Core/Settings/Pages/General/PreserveUserInput.tsx
This PR adds the option "Preserve user input" in the general settings.
Fixes #1387
=> feat: add option to clear user input after invoking action
