.travis.yml
appveyor.yml
package.json
tslint.json
yarn.lock

Added tslint with recommended rules. Please review the code and adjust the rules which do not please you. There is a vscode extension for tslint

Add tslint with recommended rules

---

package.json
src/ts/helpers/file-helpers.ts
src/ts/search-plugins/home-folder-plugin.ts
src/ts/searcher/search-plugins-searcher.ts

Use more functional code for better readability.

More functional code

---

.travis.yml
package.json
yarn.lock

Add coveralls to show coverage

Add coveralls

---

src/tests/integration/config-loader.test.ts
src/ts/config-loader.ts
src/ts/config.ts

Split up the config into multiple files so it's easier to test them

WIP: Refactor config for better testability

---

README.md

I have created a chocolatey package for ueli: https://chocolatey.org/packages/ueli/
Hope that's okay!

add choco instructions

---

src/common/config/general-options.ts
src/common/translation/english-translation-set.ts
src/common/translation/german-translation-set.ts
src/common/translation/russian-translation-set.ts
src/common/translation/translation-set.ts
src/main/main.ts
src/renderer/settings/general-settings-component.ts

Added the user option to control whether the window should stay opened after execution or not.

Added option to hide window after execution

---

src/main/plugins/application-search-plugin/mac-os-app-icon-generator.ts

Fixes issue with loading certain icons, if icon loading fails, reverts to defaultIcnsFilePath for generic icon, see issue #314

Fix for Issue #314

---

src/main/executors/commandline-executor.ts
src/main/plugins/commandline-plugin/shells.ts

Hello,
I added an ability to execute commands on PowerShell Core or WSL (aka Bash on Windows).
It's a little change, but may help someone :)
Lastly, thank you for the great software.

Commandline: PowerShell Core & WSL support

---

src/common/global-hot-key/global-hot-key-modifier.ts

This adds the super key support for opening UELI

Add super key support

---

src/main/executors/file-searchers.ts
src/main/plugins/control-panel-plugin/control-panel-items-retriever.ts
src/main/plugins/control-panel-plugin/control-panel-plugin.ts
src/main/plugins/operating-system-commands-plugin/windows-operating-system-command-repository.ts
src/main/plugins/uwp-plugin/uwp-apps-retriever.ts

Unfortunately, I cant compile this from Linux apparently (or WSL2) and I dont have the tools to do/test on Windows.
Fixes #370

Disable powershell profile loading for retrievers

---

src/main/plugins/commandline-plugin/commandline-plugin.ts
src/main/production/production-search-engine.ts

fix commandline plugin execution pending

---

src/main/executors/commandline-executor.ts
src/main/plugins/commandline-plugin/shells.ts

Shell commands needs some sanitation to run correctly. But it seems like it is not the priority number one.
Currently deployed version doesn't have sanitation as well.

Added iTerm Support.

---

src/main/plugins/application-search-plugin/windows-app-icon-generator.ts

The windows-app-icon-generator uses a Powershell script to generate the icons. The file names are passed to powershell with node-powershell's addCommand() method. These strings are encoded as UTF8. The problem is, that this is not the encoding Powershell expects. Hence Powershell can't find the files and won't create the icons. The result is that the search results are shown without a proper icon, as can be seen in issue #401 (first screenshot: https://github.com/oliverschwendener/ueli/issues/401#issuecomment-632117828).
I could not find a way to make Powershell accept UTF8 input but I found another solution: Passing the information as base64-encoded JSON string.

Fix Windows app icon generation for files with special characters

---

src/main/executors/application-searcher.ts

Run application-searcher powershell command with -NonInteractive and -NoProfile

---

src/main/plugins/browser-bookmarks-plugin/google-chrome-bookmark-repository.ts

index additional chrome bookmark roots

---

src/renderer/settings/color-picker-component.ts
styles/settings.css

add alpha slider to color picker and use hex8

---

src/main/plugins/control-panel-plugin/control-panel-plugin.ts

fix: disable autoComplete for control-panel plugin

---

src/main/plugins/uwp-plugin/uwp-plugin.ts

fix run UWP as admin

---

README.md
src/main/plugins/browser-bookmarks-plugin/browser.ts
src/main/plugins/browser-bookmarks-plugin/vivaldi-bookmark-repository.ts
src/main/production/production-search-engine.ts

Pretty much the same as #451
Related to #248

Add vivaldi browser bookmarks

---

src/main/plugins/simple-folder-search-plugin/simple-folder-search-plugin.ts

add separator to simple-folder-search autocomplete

---

src/main/favorites/electron-store-favorite-repository.ts

👋 Hello! First off thanks for making this app! Been migrating from Alfred, and loving it.
We (@nathanshelly and I) like to back up configs for stuff like ueli via Git: we store the config files in a repo, and symlink them into the right places for various applications to pick them up. We noticed, however, that when we did this with the `config.json` in `~/Library/Application Support/ueli` there were frequent updates to the file from changing `favorites`, which we're not interested in backing up.
After looking into the source a bit, we thought it might make sense to separate the user config store from the favorites store, since they're already logically separated in code. This PR changes the favorites store to be named `favorites.json`, and adds a migration step for clients that currently …

Separate the `favorites` and `userConfig` Stores

---

src/common/ipc-channels.ts
src/main/main.ts
src/renderer/renderer.ts

As suggested in #508, this makes ueli refresh indexes on F5 key press.

Refresh indexes on F5 key press

---

src/common/translation/japanese-translation-set.ts

Thank you for merging PR https://github.com/oliverschwendener/ueli/pull/736.
And then, I've found a few typo in my Japanese translation and fixed it.
I'm sorry for bothering you 🙇

Fix typo in Japanese translation

---

src/renderer/color-themes/color-themes.ts

Add nord themes: polar night and snow storm

Nord Themes

---

src/renderer/color-themes/color-themes.ts

Add Shades Of Purple (based more or less on https://github.com/ahmadawais/shades-of-purple-vscode, tested a few things to make it look as good as possible)

Add Shades of Purple Theme

---

styles/app.css

Fix search result width with enabled search result numbers

---

package-lock.json
src/common/translation/chinese-translation-set.ts
src/common/translation/czech-translation-set.ts
src/common/translation/english-translation-set.ts
src/common/translation/german-translation-set.ts
src/common/translation/japanese-translation-set.ts
src/common/translation/korean-translation-set.ts
src/common/translation/portuguese-translation-set.ts
src/common/translation/russian-translation-set.ts
src/common/translation/spanish-translation-set.ts
src/common/translation/translation-set.ts
src/common/translation/turkish-translation-set.ts
src/main/plugins/operating-system-commands-plugin/windows-operating-system-command-repository.ts

Now both "Restart" and "Reboot" trigger a suggests a system restart for windows. Did not include halt for shutdown as it is not a widely used term for shutdown, it could also be confused for sleep/hibernate, resolves #638

"Reboot" also triggers system restart, resolves #638

---

README.md

`Alt` + `Spacebar` is a really useful hotkey, and I suggest it be be added in README.md.
This was my suggestion in https://github.com/oliverschwendener/ueli/issues/800#issuecomment-920792296

Mention `Alt` + `Spacebar` in README.md

---

package.json
src/common/helpers/operating-system-helpers.test.ts
src/common/helpers/operating-system-helpers.ts
src/common/operating-system.ts

Adds MacOS Monterey to list of supported OS versions

add macOS Monterey support

---

README.md
src/main/plugins/browser-bookmarks-plugin/browser.ts
src/main/plugins/browser-bookmarks-plugin/yandex-bookmark-repository.ts
src/main/production/production-search-engine.ts

Yandex Browser is about 20-30% of russian users. Chromium based, so I just define user directory path.
Icon get from wiki - https://ru.wikipedia.org/wiki/Файл:Yandex_Browser_logo.svg

Add support for Yandex Browser bookmarks

---

src/common/translation/finnish-translation-set.ts

I had a few small errors in the Finnish translation.

Small fixes to the Finnish translation

---

src/main/main.ts

Set tray icon tooltip to "ueli".

Set tray icon tooltip (fixes #905)

---

src/common/translation/japanese-translation-set.ts

Hi!
This updates Japanese translations for some untranslated strings related to font size/weight settings.

Update Japanese translations

---

README.md

Update README.md to include brew installation

---

README.md

I got this error while following the steps
https://i.imgur.com/C1zAduV.png

add correct step in Setup steps

---

src/common/translation/finnish-translation-set.ts

This PR is a continuation of PR #1011 as I sadly missed these few tiny errors in that PR.

Tiny fixes to the Finnish translation

---

src/common/global-hot-key/global-hot-key-key.ts

Add backtick hotkey

---

README.md
src/common/translation/czech-translation-set.ts
src/common/translation/english-translation-set.ts
src/common/translation/finnish-translation-set.ts
src/common/translation/german-translation-set.ts
src/common/translation/hindi-translation-set.ts
src/common/translation/italian-translation-set.ts
src/common/translation/japanese-translation-set.ts
src/common/translation/korean-translation-set.ts
src/common/translation/portuguese-translation-set.ts
src/common/translation/russian-translation-set.ts
src/common/translation/simplified-chinese-translation-set.ts
src/common/translation/spanish-translation-set.ts
src/common/translation/traditional-chinese-translation-set.ts
src/common/translation/turkish-translation-set.ts
src/common/translation/ukrainian-translation-set.ts

Update currency conversion URL in documentation and description to the current provider (https://exchangerate.host)

Update currency converter description

---

src/main/Core/IniFileParser/IniFileParser.test.ts
src/main/Core/IniFileParser/IniFileParser.ts

Fixed error handling and added test to ensure errors are thrown when appropriate

fix(IniFileParser): Fixed error handling

---

src/common/Core/Hotkey.test.ts
src/common/Core/Hotkey.ts

fix(Hotkey): Support multiple modifiers

---

src/renderer/Core/Search/Search.tsx

Reopening per https://github.com/oliverschwendener/ueli/pull/1158, with signed commits!
> Not sure why I couldn't re-open the previous PR, but once I rebased with the signed commit the option was no longer visible.

Add navigation with C-n and C-p

---

src/main/Core/FileSystemUtility/Contract/FileSystemUtility.ts
src/main/Core/FileSystemUtility/NodeJsFileSystemUtility.ts

feat(FileSystemUtility): added option to read directory recursively

---

src/main/Core/FileSystemUtility/Contract/FileSystemUtility.ts
src/main/Core/FileSystemUtility/NodeJsFileSystemUtility.test.ts
src/main/Core/FileSystemUtility/NodeJsFileSystemUtility.ts

This PR adds tests for the `NodeJsFileSystemUtility` which allows us to make changes in the future with higher confidence that we don't break anything.

test: NodeJsFileSystemUtility

---

src/main/Extensions/VSCode/VSCodeExtension.ts
src/main/Extensions/VSCode/VSCodeModule.ts

Add remote uri support which should fix #1196
Also added some logging to help debug any issues in the future of generating the items

Add remote uri support

---

src/main/Extensions/CurrencyConversion/CurrencyConversion.test.ts
src/main/Extensions/CurrencyConversion/CurrencyConversion.ts
src/main/Extensions/CurrencyConversion/Rates.ts
src/main/Extensions/CurrencyConversion/convert.test.ts
src/main/Extensions/CurrencyConversion/convert.ts

This PR adds tests for the CurrencyConversion extension

test: currency conversion

---

src/main/Core/TrayIcon/TrayIconManager.test.ts
src/main/Core/TrayIcon/TrayIconManager.ts

feat(TrayIcon): show tooltip on hover

---

src/main/Extensions/BrowserBookmarks/ChromiumBrowserBookmarkRepository.test.ts

test(BrowserBookmarks): Added test for ChromiumBrowserBookmarkRepository

---

src/main/Extensions/ApplicationSearch/ApplicationSearch.test.ts
src/main/Extensions/ApplicationSearch/ApplicationSearch.ts
src/main/Extensions/ApplicationSearch/Settings.ts
src/main/Extensions/ApplicationSearch/macOS/MacOsApplicationRepository.ts
src/renderer/Extensions/ApplicationSearch/MacOs/MacOsSettings.tsx

feat: added advanced mdfind filtering options

---

src/main/Extensions/ApplicationSearch/macOS/MacOsApplicationRepository.test.ts

This PR adds a unit test for the MacOsApplicationRepository

Added test for MacOsApplicationRepository

---

src/main/Core/ImageGenerator/Linux/LinuxAppIconExtractor.ts
src/main/Extensions/ApplicationSearch/Linux/LinuxApplicationRepository.ts

Fixes and improvements for changes made in #1233

fix: Refactor for typescript strict mode

---

src/main/Extensions/ApplicationSearch/Linux/LinuxApplication.test.ts
src/main/Extensions/ApplicationSearch/Windows/WindowsApplication.test.ts
src/main/Extensions/ApplicationSearch/macOS/MacOsApplication.test.ts

This PR adds tests for the following classes:
- LinuxApplication
- MacOsApplication
- WindowsApplication

test: application classes

---

src/main/Extensions/ApplicationSearch/Windows/WindowsApplicationRepository.test.ts

test: added test for WindowsApplicationRepository

---

src/main/Core/CommandlineUtility/Contract/CommandlineUtility.ts
src/main/Core/CommandlineUtility/NodeJsCommandlineUtility.test.ts
src/main/Core/CommandlineUtility/NodeJsCommandlineUtility.ts
src/main/Core/PowershellUtility/Contract/PowershellUtility.ts
src/main/Core/PowershellUtility/PowershellUtility.test.ts
src/main/Core/PowershellUtility/PowershellUtility.ts
src/main/Extensions/ApplicationSearch/Linux/LaunchDesktopFileActionHandler.ts
src/main/Extensions/ApplicationSearch/Windows/WindowsApplicationRepository.ts
src/main/Extensions/ApplicationSearch/macOS/MacOsApplicationRepository.test.ts
src/main/Extensions/FileSearch/macOS/MdfindFileSearcher.ts

This PR adds a parameter `maxBuffer` when executing cli programs.
Might fix #1189

refactor(CommandlineUtility): added `maxBuffer` option

---

src/main/Extensions/CustomWebSearch/CustomWebSearchExtension.ts

This PR fixes some typos in the Custom Web Search extension.

fix(CustomWebSearch): typos

---

src/main/Extensions/CustomWebSearch/CustomWebSearchExtension.test.ts
src/main/Extensions/CustomWebSearch/CustomWebSearchExtension.ts

allow different results from multiple search engines

---

eslint.config.mjs
src/main/Core/BrowserWindow/BrowserWindowCreator/BrowserWindowCreator.test.ts
src/main/Core/PowershellUtility/PowershellUtility.ts
src/main/Core/TrayIcon/TrayCreator.test.ts
src/main/Extensions/ColorConverter/ColorConverterExtension.ts
src/main/Extensions/CustomWebSearch/CustomWebSearchExtension.ts
src/main/Extensions/JetBrainsToolbox/JetBrainsToolboxExtension.ts
src/main/Extensions/TerminalLauncher/TerminalLauncherExtension.ts
src/main/Extensions/VSCode/VSCodeExtension.ts

This PR enforces classes to explicitly declare members as "public" or "private".

eslint: enforce class member accessibility

---

src/main/Core/BrowserWindow/BrowserWindowModule.ts
src/main/Core/NativeTheme/NativeThemeModule.ts

chore: replace `nativeTheme.addListener` with `nativeTheme.on`

---

src/common/Core/Search/InternalSearchFilter.ts
src/common/Core/Search/SearchFilter.ts
src/common/Core/Search/SearchResultItemFilter.ts
src/common/Core/Search/fuzzySortFilter.test.ts
src/common/Core/SearchResultItemActionUtility/createAddToFavoritesAction.test.ts
src/common/Core/SearchResultItemActionUtility/createAddToFavoritesAction.ts
src/common/Core/SearchResultItemActionUtility/createCopyToClipboardAction.test.ts
src/common/Core/SearchResultItemActionUtility/createCopyToClipboardAction.ts
src/common/Core/SearchResultItemActionUtility/createExcludeFromSearchResultsAction.test.ts
src/common/Core/SearchResultItemActionUtility/createExcludeFromSearchResultsAction.ts
src/common/Core/SearchResultItemActionUtility/createInvokeExtensionAction.ts
src/common/Core/SearchResultItemActionUtility/createOpenFileAction.test.ts
src/common/Core/SearchResultItemActionUtility/createOpenFileAction.ts
src/common/Core/SearchResultItemActionUtility/createOpenUrlSearchResultAction.test.ts
src/common/Core/SearchResultItemActionUtility/createOpenUrlSearchResultAction.ts
src/common/Core/SearchResultItemActionUtility/createRemoveFromFavoritesAction.test.ts
src/common/Core/SearchResultItemActionUtility/createRemoveFromFavoritesAction.ts
src/common/Core/SearchResultItemActionUtility/createShowItemInFileExplorerAction.test.ts
src/common/Core/SearchResultItemActionUtility/createShowItemInFileExplorerAction.ts

refactor: simplified imports

---

src/main/Extensions/CustomWebSearch/CustomWebSearchExtension.ts

This PR removes an unused method.

refactor: removed unused method

---

src/main/Core/CommandlineUtility/Contract/CommandlineUtility.ts
src/main/Core/PowershellUtility/Contract/PowershellUtility.ts
src/main/Core/XmlParser/Contract/XmlParser.ts

refactor: improved jsdoc comments

---

src/main/Extensions/CustomWebSearch/CustomWebSearchExtension.ts
src/renderer/Extensions/CustomWebSearch/CustomWebSearchDialog.tsx
src/renderer/Extensions/CustomWebSearch/CustomWebSearchSettings.tsx

already added search engines can now be edited

implement edit for custom web search

---

src/common/Core/InstantSearchResultItems.ts
src/common/Core/createEmptyInstantSearchResult.ts
src/common/Core/index.ts

This PR extracts the function `createEmptyInstantSearchResult` into a separate file.

refactor: extract function into separate file

---

src/renderer/Core/I18n/getCoreResources.ts

fix: use better translations for "blur" event

---

src/renderer/Core/Theme/ThemeProvider.tsx
src/renderer/Core/Theme/getFluentUiTheme.test.ts
src/renderer/Core/Theme/getFluentUiTheme.ts

Fix bug when theme name cant be resolved to fluent ui theme

---

src/main/Core/BrowserWindow/BrowserWindowModule.ts
src/main/Core/BrowserWindow/HtmlLoader/HtmlLoader.test.ts
src/main/Core/BrowserWindow/HtmlLoader/HtmlLoader.ts

fix: load static file when vite dev server url is not available

---

src/main/Extensions/Workflow/WorkflowExtension.ts

Hide window after invoking workflow

---

src/main/Extensions/FileSearch/FileSearch.test.ts
src/main/Extensions/FileSearch/Windows/EverythingFileSearcher.ts

Fixed invocation of Everything CLI (part of #503)

Fixed invocation of Everything CLI

---

src/renderer/Extensions/CustomWebSearch/CustomWebSearchDialog.tsx
src/renderer/Extensions/CustomWebSearch/CustomWebSearchSettings.tsx

Fixed bug #1350 and implemented feature request #1351.

Fixed bug with untrimmed prefixes and moved Add button to top

---

src/renderer/Core/Components/BasicSearch.tsx

Added navigation back in basic search (e.g. FileSearch) using Esc key

Added navigation back in basic search (e.g. FileSearch) using Esc key

---

src/renderer/Core/Search/Search.tsx

Add keyboard shortcut to set focus on search bar

---

src/main/Extensions/ApplicationSearch/ApplicationSearch.ts
src/renderer/Extensions/ApplicationSearch/Windows/FileExtensions.tsx
src/renderer/Extensions/ApplicationSearch/Windows/Folders.tsx
src/renderer/Extensions/ApplicationSearch/Windows/WindowsSettings.tsx

Additionally fixes missing translations.
Fixes #264

Add folder path validation in windows application search settings

---

electron-builder.config.js

This PR adds arm64 builds on Linux.
Fixes #1378

feat: add arm64 build on Linux

---

package-lock.json
package.json

Update vite to 6.2.0

---

src/main/Core/TrayIcon/ContextMenuTemplateProvider.test.ts
src/main/Core/TrayIcon/ContextMenuTemplateProvider.ts

Reordered menu and added seperators (Show / Settings-related / Quit)

Reordered tray menu and introduced seperators

---

src/main/Extensions/Base64Conversion/Base64Conversion.ts
src/main/Extensions/UuidGenerator/UuidGeneratorExtension.ts

It is a great app with multilingual support.
However, there were a few places where the translation function was not implemented.
I have added implementation where I can fix it quickly.

insert nameTranslation() to Base64, UuidGen

---

src/main/Core/FileSystemUtility/Contract/FileSystemUtility.ts
src/main/Core/FileSystemUtility/NodeJsFileSystemUtility.test.ts
src/main/Core/FileSystemUtility/NodeJsFileSystemUtility.ts

feat(FileSystemUtility): add `writeFile`

---

package.json

Bump sharp from v0.33.5 to v0.34.0

---

src/main/Extensions/ApplicationSearch/Linux/LinuxApplicationRepository.ts

This PR replaces a `.forEach()` with a `for .. of` loop to be more consistent with the rest of the code base. Additionally it improves the warning when a given path is not a directory. `for..of` loops have also additional advantages over `.forEach()` for example:
- Supports await inside the loop (in async functions)
- Easier to break, continue, or return
- Slightly better performance in some cases
- More familiar if coming from other programming languages

refactor(ApplicationSearch): replace `.forEach()` with `for..of`

---

src/main/Core/ImageGenerator/FaviconProvider/DuckDuckGoFaviconProvider.ts
src/main/Core/ImageGenerator/FaviconProvider/FaviconProvider.ts
src/main/Core/ImageGenerator/FaviconProvider/FaviconeFaviconProvider.ts
src/main/Core/ImageGenerator/FaviconProvider/GoogleFaviconProvider.ts
src/main/Core/ImageGenerator/FaviconProvider/index.ts
src/main/Core/ImageGenerator/ImageGeneratorModule.ts
src/main/Core/ImageGenerator/UrlImageGenerator.test.ts
src/main/Core/ImageGenerator/UrlImageGenerator.ts
src/renderer/Core/Settings/Pages/General/UrlImageGenerator.tsx

This PR adds a new favicon provider: DuckDuckGo

feat(FaviconProvider): add DuckDuckGo

---

src/main/Core/TrayIcon/TrayIconManager.test.ts
src/main/Core/TrayIcon/TrayIconManager.ts
src/main/Core/TrayIcon/TrayIconModule.ts
src/renderer/Core/I18n/getCoreResources.ts
src/renderer/Core/Settings/Pages/General/General.tsx
src/renderer/Core/Settings/Pages/General/TrayIcon/TrayIconSettings.tsx
src/renderer/Core/Settings/Pages/General/TrayIcon/index.tsx

This PR adds the ability to show/hide the tray icon.
Fixes #1385

feat: add option to show/hide tray icon

---

src/common/Extensions/SimpleFileSearch/FolderSetting.ts
src/main/Core/FileSystemUtility/Contract/FileSystemUtility.ts
src/main/Core/FileSystemUtility/NodeJsFileSystemUtility.test.ts
src/main/Core/FileSystemUtility/NodeJsFileSystemUtility.ts
src/main/Extensions/SimpleFileSearch/SimpleFileSearchExtension.ts
src/renderer/Extensions/SimpleFileSearch/EditDialog.tsx
src/renderer/Extensions/SimpleFileSearch/FolderListItem.tsx

This PR adds the option to exclude hidden files as requested in #1214.

feat(SimpleFileSearch): add the option to exclude hidden files

---

src/common/Extensions/Workflow/Workflow.ts
src/main/Extensions/Workflow/WorkflowExtension.ts
src/renderer/Extensions/Workflow/WorkflowForm.tsx

This PR adds the option to enable "require confirmation" for workflows as requested in #1126.

feat(Workflow): add option to require confirmation
